### ISSUE TITLE
Generic chart

### ISSUE THREAD

**Issue by roaldarbol** [BrianPugh/magnetometer#2]
This is such a cool implementation! What would be needed to make the graph into a generic method which takes a list of variable names and values (leaving the type of sensor and getting the data to the user)? I tried to have a look at the code, and it seems there would have to be some re-structuring to make it softer coded, iterating through the provided variable names rather than hardcoding them.

**Comment by BrianPugh** [comment]
so it depends on how much of the existing code you would like to use. The `asciichartpy.py` is standalone and modified to be compatible with the Rich library. The data provided can be a list of lists for multiple plots on the same axis and it returns a string that when printed represents the chart. All the logic in `main.py` is a bit round about, but thats just how Textual works.

**Comment by roaldarbol** [comment]
Oh, cool! Yeah, I'd probably just want to use it without Textual (at least in the foreseeable future). All these wonderful new tools are overwhelming me somewhat. 😉 I'll dig into your `asciichartpy.py` file and try making it work for me - thanks!
